const PROJECTS = [
    'mt-disturbances',
    'mt-springfield-magnolia',
    'mt-pstn',
    'mt-facade',
    'mt-balance',
    'mt-util',
    'mt-simcard',
    'mt-springfield-correspondence',
    'mt-springfield-order',
    'mt-springfield-offer',
    'mt-springfield-subscription',
    'mt-springfield-invoice',
    'mt-springfield-telia-life',
    'mt-recommendations',
    'mt-mandate',
    'mt-tv',
    'mt-springfield-family',
    'mt-int-offer',
    'mt-int-callforwarding',
    'mt-int-subscription',
    'mt-int-voip',
    'springfield-login',
    'mt-smart-wifi-plus',
    'mt-ais-offeringdata',
    'mt-springfield-account',
    'mt-services-repayment',
    'transfer-agreement',
    'history-usage',
    'mt-subscription-details',
]

const ENVIRONMENTS = [
    'test',
    'at',
    'mite',
    'sit',
]
